server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: model-management-route
          uri: ${MODEL_MANAGEMENT_BASE_URL:http://localhost:8081}
          predicates:
            - Path=/api/models/**
        - id: statistics-route
          uri: ${STATISTICS_BASE_URL:http://localhost:8082}
          predicates:
            - Path=/api/statistics/**
